# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.searchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchBtn.setCheckable(True)
        self.searchBtn.setAutoExclusive(False)
        self.searchBtn.setObjectName("searchBtn")
        self.gridLayout.addWidget(self.searchBtn, 2, 2, 1, 1)
        self.movieName = QtWidgets.QLineEdit(self.centralwidget)
        self.movieName.setObjectName("movieName")
        self.gridLayout.addWidget(self.movieName, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.searchRes = QtWidgets.QTableWidget(self.centralwidget)
        self.searchRes.setMinimumSize(QtCore.QSize(500, 0))
        self.searchRes.setObjectName("searchRes")
        self.searchRes.setColumnCount(3)
        self.searchRes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.searchRes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchRes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchRes.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.searchRes, 3, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 520, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "影视资源搜索_sjs v1.0"))
        self.searchBtn.setText(_translate("MainWindow", "开始搜索"))
        self.label.setText(_translate("MainWindow", "电影名:"))
        item = self.searchRes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "来源"))
        item = self.searchRes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        item = self.searchRes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "链接"))
        self.label_2.setText(_translate("MainWindow", "搜索后复制链接地址进入浏览器即可访问"))
